# Generated by Django 4.2.1 on 2023-05-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razor_payment_status',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razord_order_id',
            new_name='payment_status',
        ),
    ]
