# Generated by Django 4.2.1 on 2023-05-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_rename_razor_payment_status_payment_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('shipped', 'shipped'), ('canceled', 'canceled')], default='pending', max_length=50),
        ),
    ]
